<?php

putenv("DISPLAY_ERRORS_DETAILS=" . true);

putenv("GERENCIADOR_DE_LOJAS_SQLSERVER_HOST=");
putenv("GERENCIADOR_DE_LOJAS_SQLSERVER_DBNAME=");
putenv("GERENCIADOR_DE_LOJAS_SQLSERVER_USER=");
putenv("GERENCIADOR_DE_LOJAS_SQLSERVER_PASSWORD=");
putenv("GERENCIADOR_DE_LOJAS_SQLSERVER_PORT=");

putenv("JWT_SECRET_KEY=");
